_project:
    resource: "@TashiProjectBundle/Controller/ProjectController.php"
    type:     annotation
_category:
    resource: "@TashiProjectBundle/Controller/MasterController.php"
    type:     annotation